# Generated by Django 5.0.6 on 2024-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_APP', '0003_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temporary_field',
            field=models.CharField(default='temporary', max_length=100),
        ),
    ]
