# Generated by Django 5.0.6 on 2024-07-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_temporary_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='temporary_field',
        ),
    ]
